<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ME314_midterm_240006078</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="midterm_assignment_files/libs/clipboard/clipboard.min.js"></script>
<script src="midterm_assignment_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="midterm_assignment_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="midterm_assignment_files/libs/quarto-html/popper.min.js"></script>
<script src="midterm_assignment_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="midterm_assignment_files/libs/quarto-html/anchor.min.js"></script>
<link href="midterm_assignment_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="midterm_assignment_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="midterm_assignment_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="midterm_assignment_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="midterm_assignment_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#submission-instructions" id="toc-submission-instructions" class="nav-link active" data-scroll-target="#submission-instructions">Submission Instructions</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#question-1-data-and-programming-10-marks" id="toc-question-1-data-and-programming-10-marks" class="nav-link" data-scroll-target="#question-1-data-and-programming-10-marks">Question 1: Data and Programming (10 Marks)</a></li>
  <li><a href="#question-2-data-generating-processes-10-marks" id="toc-question-2-data-generating-processes-10-marks" class="nav-link" data-scroll-target="#question-2-data-generating-processes-10-marks">Question 2: Data Generating Processes (10 Marks)</a></li>
  <li><a href="#question-3-linear-regression-10-marks" id="toc-question-3-linear-regression-10-marks" class="nav-link" data-scroll-target="#question-3-linear-regression-10-marks">Question 3: Linear Regression (10 Marks)</a></li>
  <li><a href="#question-4-causal-inference-10-marks" id="toc-question-4-causal-inference-10-marks" class="nav-link" data-scroll-target="#question-4-causal-inference-10-marks">Question 4: Causal Inference (10 Marks)</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ME314_midterm_240006078</h1>
<p class="subtitle lead">LSE ME314: Introduction to Data Science and Machine Learning</p>
</div>



<div class="quarto-title-meta">

    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">July 22, 2025</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="submission-instructions" class="level2">
<h2 class="anchored" data-anchor-id="submission-instructions">Submission Instructions</h2>
<p>This assignment is due <strong>Wednesday 23rd of July 2025 at 9am</strong>:</p>
<ul>
<li><p>Please submit this assignment via the submission portal on Moodle.</p></li>
<li><p>Please submit your assignment as both a knitted&nbsp;.html file and the corresponding&nbsp;.qmd file; PDFs or other formats will not be accepted. You must name the files accordingly: “ME314_midterm_XXXXXXXXX” where XXXXXXXXX should be replaced with your LSE candidate number. The candidate number is your LSE ID number (not your Library number).</p></li>
<li><p>We will assess your assignment based on how well you apply the methods and reasoning introduced during our lectures and seminar sessions.</p></li>
</ul>
<p><em>Please note, we will not contact you to recompile documents if they are submitted in the wrong format. It is your responsibility to ensure you submit your work correctly. Failure to do so will result in a mark of 0 for that assignment.</em></p>
<p><em>You are expected to complete this problem set yourself without excessive use of generative AI. You should use sample code from seminars and lectures, and adapt it to the questions below on your own. You may consult generative AI to answer general questions and/or supplement your learning, but not to complete the exercises. Markers have lots of experience reviewing student work, and they can usually tell when generative AI substantially completed an assignment. If we suspect you have done this, we will mark your answers accordingly.</em></p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This is a <em>summative</em> assignment, and will constitute 25% of your final grade. You should use feedback from seminars to ensure you meet both the substantive and formatting standards for this module.</p>
<p>For clarity, the formatting requirements for this assignment are:</p>
<ul>
<li><p>Unless otherwise stated, you must present all results in full sentences, as you would in a report or academic piece of writing. Keep it as concise as possible!</p></li>
<li><p>If the exercise requires generating a table or figure, you should include at least one sentence introducing and explaining it. E.g. “The table below reports the counts of Wikipedia articles mentioning the LSE, by type of article.”</p></li>
<li><p>Unless stated otherwise, all code used to answer the exercises should be included in the code chunks for each exercise.</p></li>
<li><p>All code should be annotated with comments, to help the marker understand what you have done.</p></li>
<li><p>Your output should be replicable and results should be reproducible. Any result/table/figure that cannot be traced back to your code will not be marked.</p></li>
</ul>
<section id="question-1-data-and-programming-10-marks" class="level3">
<h3 class="anchored" data-anchor-id="question-1-data-and-programming-10-marks">Question 1: Data and Programming (10 Marks)</h3>
<p>This question is designed to test your ability to (1) load and clean data, (2) summarise and transform data, (3) perform simple for-loop operations with programming, and, (4) devise control flows.</p>
<p><strong>1.1 Loading and cleaning data:</strong></p>
<ul>
<li><p>Set the random seed to 123. The code is included. This is for reproducibility and must be executed for consistent reproduction of the same outputs.</p></li>
<li><p>After this, load the <code>airquality</code> dataset, which is built-in with R. Inspect the structure of the dataframe with <code>str()</code>.</p></li>
<li><p>Next, drop all rows in which any column contains an NA value.</p></li>
<li><p>After this, remove all rows where the value of <code>Ozone</code> is more than 2 standard deviations <strong>above</strong> the mean <code>Ozone</code> level in our dataset. Name this new dataframe <code>aq_clean</code>.</p></li>
<li><p>Finally, use the <code>dim()</code> function to print the dimensions of the <code>aq_clean</code> dataframe. How many rows are remaining?</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the airquality dataset into my own object then observed its structure</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"airquality"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>aq <span class="ot">&lt;-</span> airquality</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(aq)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   153 obs. of  6 variables:
 $ Ozone  : int  41 36 12 18 NA 28 23 19 8 NA ...
 $ Solar.R: int  190 118 149 313 NA NA 299 99 19 194 ...
 $ Wind   : num  7.4 8 12.6 11.5 14.3 14.9 8.6 13.8 20.1 8.6 ...
 $ Temp   : int  67 72 74 62 56 66 65 59 61 69 ...
 $ Month  : int  5 5 5 5 5 5 5 5 5 5 ...
 $ Day    : int  1 2 3 4 5 6 7 8 9 10 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># delete rows with NA then observing its dimension to see how many rows were deleted</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>aq <span class="ot">=</span> <span class="fu">na.omit</span>(aq)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(aq)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 111   6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># loading dplyr in order to filter and clean the dataset some more</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filtering the dataset to remove all rows were the value of Ozone is more than 2sd above the mean</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># finding the mean and sd of Ozone then the max value we want Ozone to be</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>oz_mean <span class="ot">=</span> <span class="fu">mean</span>(aq[[<span class="st">"Ozone"</span>]]) </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>oz_sd <span class="ot">=</span> <span class="fu">sd</span>(aq[[<span class="st">"Ozone"</span>]])</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>oz_max <span class="ot">=</span> oz_mean <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>oz_sd</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># filtering the dataframe to only include up to the max value (2sd above the mean) and loading it into aq_clean</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>aq_clean <span class="ot">=</span> aq <span class="sc">%&gt;%</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(Ozone <span class="sc">&lt;=</span> oz_max)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co"># finding the dimensions of aq_clean</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(aq_clean) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 105   6</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer</strong>: There are 105 rows left in the dataframe.</p>
</div>
</div>
</div>
<p><strong>1.2 Summarising and transforming data:</strong></p>
<p>Take your <code>aq_clean</code> dataframe and follow these steps in order:</p>
<ul>
<li><p>Add a new column titled <code>Temp_Cels</code> which contains the temperature in Celsius using the <code>mutate()</code> function from the <code>dplyr</code> package in the <code>tidyverse.</code> The data is currently in Fahrenheit.</p></li>
<li><p>Use <code>group_by()</code> and <code>summarise()</code> to calculate the average <code>Wind</code> and <code>Temp_Cels</code> per month.</p></li>
<li><p>Which month has the highest average Wind? What is this value?</p></li>
<li><p>Which month has the median average Temp_Cels? What is this value?</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># loaded the tidyverse library</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ readr     2.1.5
✔ ggplot2   3.5.2     ✔ stringr   1.5.1
✔ lubridate 1.9.4     ✔ tibble    3.2.1
✔ purrr     1.0.4     ✔ tidyr     1.3.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># adding a new column with the temperature in Celcius</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>aq_clean <span class="ot">=</span> aq_clean <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="st">"Temp_Cels"</span> <span class="ot">=</span> (Temp <span class="sc">-</span> <span class="dv">32</span>) <span class="sc">*</span> (<span class="dv">5</span><span class="sc">/</span><span class="dv">9</span>))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the average wind and temperature in Celcius by month </span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>aq_sum <span class="ot">=</span> aq_clean <span class="sc">%&gt;%</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(Month) <span class="sc">%&gt;%</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">mean</span>(Wind), <span class="fu">mean</span>(Temp_Cels))</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co"># filtering to get the row with the max mean wind</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>aq_sum <span class="sc">%&gt;%</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(aq_sum[[<span class="st">"mean(Wind)"</span>]] <span class="sc">==</span> <span class="fu">max</span>(aq_sum[[<span class="st">"mean(Wind)"</span>]]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  Month `mean(Wind)` `mean(Temp_Cels)`
  &lt;int&gt;        &lt;dbl&gt;             &lt;dbl&gt;
1     6         12.2              25.7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filtering to get the row with the median mean temperature in celcius</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>aq_sum <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(aq_sum[[<span class="st">"mean(Temp_Cels)"</span>]] <span class="sc">==</span> <span class="fu">median</span>(aq_sum[[<span class="st">"mean(Temp_Cels)"</span>]]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  Month `mean(Wind)` `mean(Temp_Cels)`
  &lt;int&gt;        &lt;dbl&gt;             &lt;dbl&gt;
1     6         12.2              25.7</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer</strong>: Month 6 has the highest average wind with 12.2mph. Month 6 also has the median average temperature value at 25.7 degrees Celcius.</p>
</div>
</div>
</div>
<p><strong>1.3 For-loop operations:</strong></p>
<p>You have cleaned air‑quality data in a data frame <code>aq_clean,</code> and want to quantify the variability of the sample mean of <code>Solar.R.</code> In this subquestion, we will use a for-loop to get a bootstrapped standard error for the mean of the variable Solar.R.</p>
<ul>
<li><p>Use the <code>mean()</code> function to calculate the sample mean of <code>aq_clean$Solar.R</code>.</p></li>
<li><p>Assign <code>1000</code> to a numeric vector of length 1 named <code>n_boot</code>.</p></li>
<li><p>Pre‑allocate an empty numeric vector <code>boot_means</code> of length<code>n_boot</code> using the <code>numeric()</code> function.</p></li>
<li><p>In a for‑loop over i in 1:<code>n_boot</code>:</p>
<ul>
<li><p>Draw a bootstrap sample of size <code>length(aq_clean$Solar.R)</code> using the function <code>sample()</code> with replacement from <code>aq_clean$Solar.R</code></p></li>
<li><p>Compute its mean and store it in <code>boot_means[i]</code></p></li>
</ul></li>
<li><p>Finally, use <code>boot_means</code> and the <code>sd()</code> function to estimate the boostrapped standard error for the mean of the variable <code>Solar.R</code>.</p></li>
<li><p>Report both the sample mean (calculated in step 1) and its bootstrapped standard error.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find the sample mean of Solar.R</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>sr_mean <span class="ot">=</span> <span class="fu">mean</span>(aq_clean<span class="sc">$</span>Solar.R)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of bootstrap replicates</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>n_boot <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Pre-allocate storage</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    boot_means <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n_boot)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Loop to generate bootstrap means</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_boot) {</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>        <span class="co">#sampling from the Solar.R data</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>        sample <span class="ot">=</span> <span class="fu">sample</span>(aq_clean<span class="sc">$</span>Solar.R, <span class="fu">length</span>(aq_clean<span class="sc">$</span>Solar.R), <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>        <span class="co">#storing the mean of the sample each time</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>        boot_means[i] <span class="ot">=</span> <span class="fu">mean</span>(sample)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="co"># find the sd of the bootstraped means</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>sr_sd <span class="ot">=</span> <span class="fu">sd</span>(boot_means)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Mean of Solar.R     :"</span>, sr_mean, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean of Solar.R     : 181.8667 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Bootstrap std. error     :"</span>, sr_sd , <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bootstrap std. error     : 8.774674 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer</strong>: The sample mean is 181.8667 lang and the standard error is 8.774674 lang.</p>
</div>
</div>
</div>
<p><strong>1.4 Control flow:</strong></p>
<p>Use an if/else control flow to label days by whether they exceed the mean <code>Ozone</code> level.</p>
<ul>
<li><p>Recalculate the mean <code>Ozone</code> using the current <code>aq_clean</code> dataframe.</p></li>
<li><p>Create a new categorical variable in <code>aq_clean</code> titled <code>Ozone_Status</code> with the label “High” if the row’s Ozone exceeds the mean, and “Low” if not. You must use <code>ifelse()</code> for this.</p></li>
<li><p>Calculate how many “High” days there are and report this number.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># recalculating the mean of the Ozone</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>oz_mean <span class="ot">=</span> <span class="fu">mean</span>(aq_clean<span class="sc">$</span>Ozone)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>oz_mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37.19048</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creating a new categorical variable</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>aq_clean <span class="ot">=</span> aq_clean <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="st">"Ozone_Status"</span> <span class="ot">=</span> <span class="fu">ifelse</span>((aq_clean[[<span class="st">"Ozone"</span>]] <span class="sc">&gt;</span> oz_mean), <span class="st">"High"</span>, <span class="st">"Low"</span>))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># The table below counts how many values are in each status (high or low).</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(aq_clean<span class="sc">$</span>Ozone_Status)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
High  Low 
  40   65 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer</strong>: There are 40 “High” days.</p>
</div>
</div>
</div>
</section>
<section id="question-2-data-generating-processes-10-marks" class="level3">
<h3 class="anchored" data-anchor-id="question-2-data-generating-processes-10-marks">Question 2: Data Generating Processes (10 Marks)</h3>
<p>Imagine you want to examine how study habits affect exam scores among 300 students. However, the distribution of study time is skewed: most students study little, but a few study a lot. The exam scores are generated using the following model: <span class="math display">\[
\text{exam\_score} = 60 + 1.5 \times \text{study\_hours} + \epsilon
\]</span></p>
<p>where <span class="math inline">\(\epsilon \sim \mathcal{N}(0,8)\)</span> represents random noise.</p>
<p><strong>2.1 Simulate the data:</strong></p>
<ul>
<li><p>Generate a vector called <code>study_hours</code> for 300 students using an exponential distribution, scaled so that most students study between 0 and 20 hours.</p></li>
<li><p>Generate a vector called <code>group</code> with two unique values: “online” and “in-person” (150 students each), randomly assigned.</p></li>
<li><p>Generate <code>exam_score</code> using the data generating process defined above, adding random noise <span class="math inline">\(\epsilon\)</span> drawn from a normal distribution with mean 0 and standard deviation 8.</p></li>
<li><p>Create a data frame called <code>exam_data</code> with the three variables.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set seed for reproducibility</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># setting the number of students</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>n_students <span class="ot">=</span><span class="dv">300</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I chose a rate of 1/4 since then the expected study time would be around 4 hours (expectation of an exponential is 1/lambda) and the majority of students would be skewed towards the lower end of studying. I made sure the majority of students studied between 0 and 20 hours through looking at the histogram and summary statistics. 75% of the students study 6 hours or less. The maximum anyone studied is 28 hours. This makes sense as a max as that student’s score would be around 100 (actually, 102) according to the formula we specfied. 100 is the max score you can get on an exam but the randomized error simulated seems to account for the overestimate. Similarly, the randomize error epsilon accounts for the scores below 60.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generating study hours through exponential distribution then creating a histogram and reading the summary</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>study_hours <span class="ot">=</span> <span class="fu">rexp</span>(n_students, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">4</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(study_hours, <span class="at">main =</span> <span class="st">"Distribution of Study Hours"</span>, <span class="at">xlab =</span> <span class="st">"Hours Studied"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="midterm_assignment_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(study_hours)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
 0.01747  1.27188  3.36918  4.06096  5.91868 28.84403 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generating the options the group can sample from</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>status <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"online"</span>, <span class="st">"in-person"</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># drawing randomly the status of students online or in person by sampling to create group with 150 each</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>group <span class="ot">=</span> <span class="fu">sample</span>(<span class="fu">rep</span>(status, <span class="at">each =</span> <span class="dv">150</span>))</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># generating exam scores using the given formula and simulating the normally distribute errors</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>epsilon <span class="ot">=</span> <span class="fu">rnorm</span>(n_students, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span><span class="dv">8</span>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>exam_score <span class="ot">=</span> <span class="dv">60</span> <span class="sc">+</span> (<span class="fl">1.5</span><span class="sc">*</span>study_hours) <span class="sc">+</span> epsilon</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="co"># creating the dataframe with the three variables then checking the creating by head</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>exam_data <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">study_hours =</span> study_hours, </span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>                        <span class="at">group =</span> group, </span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>                        <span class="at">exam_score =</span> exam_score)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(exam_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  study_hours     group exam_score
1   3.3738290 in-person   64.04737
2   2.3064411    online   54.81631
3   5.3162195    online   69.37398
4   0.1263094    online   50.66150
5   0.2248439    online   59.90330
6   1.2660049 in-person   48.42168</code></pre>
</div>
</div>
<p><strong>2.2 Visualize the data using ggplot2:</strong></p>
<ul>
<li><p>Create a scatter plot of <code>exam_score</code> versus <code>study_hours</code>, with points colored by <code>group</code>.</p></li>
<li><p>Make sure to use good design choices, such as adequate labels for the axes and an informative title.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># loading ggplot2 to plot</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The plot below displays the relationship between how many hours a student studied and their exam scores for 300 students, colored by which group the student is in (Online or In-Person).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#generating the plot</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">=</span> <span class="fu">ggplot</span>(<span class="at">data=</span>exam_data) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> study_hours, <span class="at">y =</span> exam_score, </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">color =</span> group)) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>        <span class="fu">labs</span>(</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">title =</span> <span class="st">"Relationship Between Hours Studied and Student Exam Scores"</span>, </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span> <span class="st">"Hour(s) Studied"</span>, </span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="st">"Exam Score"</span>)</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="midterm_assignment_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>2.3 Describe the plot you generated:</strong></p>
<p>Describe the plot. Based on the model we used to create exam_score, why is it not surprising that there is no visible difference in exam scores between students attending lectures in person and those watching online?</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer</strong>: The plot shows a generally linear trend between the hours a student studied and the exam scores they obtained for a sample of 300 students. This makes sense as we simulated the exam scores to fit along the formula <span class="math inline">\(\text{exam\_score} = 60 + 1.5 \times \text{study\_hours} + \epsilon\)</span>, which is a linear equation. The y-intercept seems to be around 60 and the slope seems to be around 1.5, as expected. This means that for every hour more a student studied, 1.5 points more were obtained on their exam. However, even if you studied 0 hours, you would still score around a 60. It was not surprising that there is no visible difference in exam scores between students attending lecture online and in-person as it was a controlled factor that was randomly sampled in our data. Within our formula for exam score, we give no consideration for group type. In the plot you can see that no matter the color, the data points are distributed similarly.</p>
</div>
</div>
</div>
</section>
<section id="question-3-linear-regression-10-marks" class="level3">
<h3 class="anchored" data-anchor-id="question-3-linear-regression-10-marks">Question 3: Linear Regression (10 Marks)</h3>
<p>For question 3, you will be working with a dataset about dogs in an animal shelter, waiting to be adopted. The dataset contains some information about dogs’ medical history and appearance and a variable <code>adoption_speed</code> that indicates how quickly the dog was adopted after being put up for adoption. The higher the value of <code>adoption_speed</code>, the quicker the dog was adopted.</p>
<p>The variables in the dataset are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 79%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>id</td>
<td>Unique identifier for each dog</td>
</tr>
<tr class="even">
<td>age</td>
<td>Age of the dog in years</td>
</tr>
<tr class="odd">
<td>vaccinated</td>
<td>Whether the dog is vaccinated (1 = Yes, 0 = No)</td>
</tr>
<tr class="even">
<td>dewormed</td>
<td>Whether the dog is dewormed (1 = Yes, 0 = No)</td>
</tr>
<tr class="odd">
<td>fur_length</td>
<td>Length of the dog’s fur in centimeters</td>
</tr>
<tr class="even">
<td>weight</td>
<td>Weight of the dog in kilograms</td>
</tr>
<tr class="odd">
<td>adoption_speed</td>
<td>Speed of adoption (higher values indicate faster adoption)</td>
</tr>
</tbody>
</table>
<p>Assume we know the data generating process (DGP) and the <strong>only</strong> causal relationships between the variables are the ones listed below. Unless otherwise noted all of these effects are linear and additive.</p>
<ul>
<li><p>Vaccination affects adoption speed.</p></li>
<li><p>Deworming affects adoption speed.</p></li>
<li><p>Age affects adoption speed.</p></li>
<li><p>Age affects vaccination status.</p></li>
<li><p>Age affects weight.</p></li>
<li><p>Dogs’ fur length has a non-linear (quadratic) effect on adoption speed.</p></li>
</ul>
<p><strong>3.1 Estimate a linear regression model</strong></p>
<p>Read in the dataset <code>dog_data.csv</code> and inspect it. Translate the DGP into a linear regression model. Read through the description of the DGP carefully and include all variables in the formula that are necessary, making sure they are specified correctly. Estimate the model using the <code>lm()</code> function, naming the lm object <code>dog_lm</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the dataset</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>dog_data <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"C:</span><span class="sc">\\</span><span class="st">Users</span><span class="sc">\\</span><span class="st">zhaom</span><span class="sc">\\</span><span class="st">Documents</span><span class="sc">\\</span><span class="st">GitHub</span><span class="sc">\\</span><span class="st">ME314</span><span class="sc">\\</span><span class="st">midterm</span><span class="sc">\\</span><span class="st">dog_data.csv"</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># inspection for first 6 rows and the structure of the dataframe and a summary of the variables</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dog_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  id age vaccinated dewormed fur_length   weight adoption_speed
1  1  15          0        1   31.63667 20.80232       58.60521
2  2  15          0        0   58.11123 25.78050       35.66223
3  3   3          0        0   66.28583 19.88588       48.79598
4  4  14          1        0   48.30661 23.01631       52.92591
5  5   3          0        0   58.58525 20.65876       50.09161
6  6  10          1        1   45.58403 24.99870       62.32790</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dog_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1000 obs. of  7 variables:
 $ id            : int  1 2 3 4 5 6 7 8 9 10 ...
 $ age           : int  15 15 3 14 3 10 2 6 11 5 ...
 $ vaccinated    : int  0 0 0 1 0 1 0 0 1 1 ...
 $ dewormed      : int  1 0 0 0 0 1 1 0 1 1 ...
 $ fur_length    : num  31.6 58.1 66.3 48.3 58.6 ...
 $ weight        : num  20.8 25.8 19.9 23 20.7 ...
 $ adoption_speed: num  58.6 35.7 48.8 52.9 50.1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dog_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       id              age          vaccinated      dewormed    
 Min.   :   1.0   Min.   : 1.00   Min.   :0.00   Min.   :0.000  
 1st Qu.: 250.8   1st Qu.: 5.00   1st Qu.:0.00   1st Qu.:0.000  
 Median : 500.5   Median : 8.00   Median :0.00   Median :0.000  
 Mean   : 500.5   Mean   : 8.08   Mean   :0.26   Mean   :0.493  
 3rd Qu.: 750.2   3rd Qu.:12.00   3rd Qu.:1.00   3rd Qu.:1.000  
 Max.   :1000.0   Max.   :15.00   Max.   :1.00   Max.   :1.000  
   fur_length        weight      adoption_speed 
 Min.   :11.75   Min.   :13.00   Min.   :21.02  
 1st Qu.:42.98   1st Qu.:19.77   1st Qu.:48.69  
 Median :50.20   Median :21.55   Median :54.06  
 Mean   :49.80   Mean   :21.62   Mean   :54.01  
 3rd Qu.:56.39   3rd Qu.:23.59   3rd Qu.:60.10  
 Max.   :88.52   Max.   :31.34   Max.   :78.13  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># running a linear regression specifying the formula as a linear function of vaccination status, deworming status, age, and a quadratic function of fur length on adoption speed as for the DGP specified.</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>dog_lm <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">formula =</span> adoption_speed<span class="sc">~</span> vaccinated <span class="sc">+</span> dewormed <span class="sc">+</span> age <span class="sc">+</span> fur_length <span class="sc">+</span> <span class="fu">I</span>(fur_length<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> dog_data) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>dog_lm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = adoption_speed ~ vaccinated + dewormed + age + fur_length + 
    I(fur_length^2), data = dog_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.1944  -2.0111  -0.0404   2.0191   8.8926 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     82.9017178  1.5257756  54.334  &lt; 2e-16 ***
vaccinated       4.8300087  0.2256282  21.407  &lt; 2e-16 ***
dewormed         1.2953737  0.1874433   6.911  8.6e-12 ***
age             -0.8946105  0.0236688 -37.797  &lt; 2e-16 ***
fur_length      -0.2277529  0.0619795  -3.675 0.000251 ***
I(fur_length^2) -0.0047264  0.0006201  -7.622  5.8e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.961 on 994 degrees of freedom
Multiple R-squared:  0.8778,    Adjusted R-squared:  0.8772 
F-statistic:  1429 on 5 and 994 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>3.2 Interpret the Regression Output</strong></p>
<p>Interpret the coefficient on age, both in terms of magnitude and statistical significance.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer</strong>: The -0.8946105 coefficient on age means that there is a negative relationship between age and adoption speed (with the other counfounders of: vaccination status, deworming status, and fur length controlled). For every year the dog ages, its speed of adoption goes down 0.894 units in value. The p-value of &lt;2e-16 indicates this finding is very signifigant to the model and the null hypothesis of age not affecting adoption speed should not be accepted. There is a very high probability that age affects adoption speed.</p>
</div>
</div>
</div>
</section>
<section id="question-4-causal-inference-10-marks" class="level3">
<h3 class="anchored" data-anchor-id="question-4-causal-inference-10-marks">Question 4: Causal Inference (10 Marks)</h3>
<p>For question 4 you will continue working with the dogs dataset from the previous question, but now you will estimate the causal effect of vaccination on adoption speed.</p>
<p><strong>4.1 Causal Graph</strong></p>
<p>Create a DAG-like graph to illustrate the causal relationships in the data. Use the <code>ggdag</code> package to create a DAG that includes all variables in the DGP. You don’t need to interpret the output. Tip: use abbreviated variable names (2-4 letters) to make the graph readable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># loading neccesary packages</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggdag)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ggdag'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    filter</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creating my dag and seeting the coordinates</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="co"># key for the dag:</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># AG = age</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># VS = vaccination status</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># DW - deworming status</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># FL = fur length</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># WT = weight</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># AS = adoption speed</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>DAG <span class="ot">=</span> <span class="fu">dagify</span>(AS <span class="sc">~</span> VS <span class="sc">+</span> DW <span class="sc">+</span> AG <span class="sc">+</span> FL,</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>  VS<span class="sc">~</span>AG,</span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>  WT<span class="sc">~</span>AG,</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">coords =</span> <span class="fu">list</span>(<span class="at">x=</span> <span class="fu">c</span>(<span class="at">WT =</span> <span class="dv">2</span>, <span class="at">AG =</span> <span class="dv">2</span>, <span class="at">VS =</span> <span class="dv">2</span>, <span class="at">DW =</span> <span class="dv">4</span>, <span class="at">AS =</span> <span class="dv">4</span>, <span class="at">FL =</span> <span class="dv">6</span>),</span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span><span class="fu">c</span>(<span class="at">WT =</span> <span class="dv">6</span>, <span class="at">AG =</span> <span class="dv">4</span>, <span class="at">VS =</span> <span class="dv">2</span>, <span class="at">DW =</span> <span class="dv">4</span>, <span class="at">AS =</span> <span class="dv">2</span>, <span class="at">FL =</span> <span class="dv">2</span>)))</span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a><span class="co"># ploting the DAG</span></span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a>DAGp <span class="ot">=</span> <span class="fu">ggdag</span>(DAG) <span class="sc">+</span></span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a>        <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb45-19"><a href="#cb45-19" aria-hidden="true" tabindex="-1"></a>        <span class="fu">remove_axes</span>()</span>
<span id="cb45-20"><a href="#cb45-20" aria-hidden="true" tabindex="-1"></a>DAGp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="midterm_assignment_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>4.2 Balance Table</strong></p>
<p>Create a balance table for the predictor variables in your model and interpret the results. You should also draw on your knowledge about the DGP when interpreting the balance table. (Tip: if you use <code>modelsummary::datasummary_balance()</code> and get an error when compiling the quarto document with the balance table, specifying the option <code>output = "markdown"</code> may fix the error.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># loading the library</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="co"># creating a dataframe without adoption speed as that is our variable of interest an without id as it doesn't affect anything, its just an identifier</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>dog_data2 <span class="ot">=</span> dog_data <span class="sc">%&gt;%</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(adoption_speed, id))</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dog_data2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  age vaccinated dewormed fur_length   weight
1  15          0        1   31.63667 20.80232
2  15          0        0   58.11123 25.78050
3   3          0        0   66.28583 19.88588
4  14          1        0   48.30661 23.01631
5   3          0        0   58.58525 20.65876
6  10          1        1   45.58403 24.99870</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># getting the data summary table</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">datasummary_balance</span>(</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>    <span class="sc">~</span>vaccinated,</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> dog_data2,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">stars =</span> T</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<!-- preamble start -->

    <script>

      function styleCell_s34u8ireasgobi6ae8ni(i, j, css_id) {
          var table = document.getElementById("tinytable_s34u8ireasgobi6ae8ni");
          var cell = table.querySelector(`[data-row="${i}"][data-col="${j}"]`);
          if (cell) {
              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);
              cell.classList.add(css_id);
          } else {
              console.warn(`Cell at (${i}, ${j}) not found.`);
          }
      }
      function insertSpanRow(i, colspan, content) {
        var table = document.getElementById('tinytable_s34u8ireasgobi6ae8ni');
        // Find the row with data-row attribute matching i
        var targetRow = table.querySelector(`tr [data-row="${i}"]`).closest('tr');
        var newRow = table.insertRow(targetRow.rowIndex);
        var newCell = newRow.insertCell(0);
        newCell.setAttribute("colspan", colspan);
        newCell.setAttribute("data-col", "0");
        newCell.setAttribute("data-row", i - 1);
        // newCell.innerText = content;
        // this may be unsafe, but innerText does not interpret <br>
        newCell.innerHTML = content;
      }
      function spanCell_s34u8ireasgobi6ae8ni(i, j, rowspan, colspan) {
        var table = document.getElementById("tinytable_s34u8ireasgobi6ae8ni");
        const targetCell = table.querySelector(`[data-row="${i}"][data-col="${j}"]`);
        if (!targetCell) {
          console.warn(`Cell at (${i}, ${j}) not found.`);
        }

        // Get all cells that need to be removed
        const cellsToRemove = [];
        for (let r = 0; r < rowspan; r++) {
          for (let c = 0; c < colspan; c++) {
            if (r === 0 && c === 0) continue; // Skip the target cell
            const cell = table.querySelector(`[data-row="${i + r}"][data-col="${j + c}"]`);
            if (cell) {
              cellsToRemove.push(cell);
            }
          }
        }

        // Remove all cells
        cellsToRemove.forEach(cell => cell.remove());

        // Set rowspan and colspan of the target cell if it exists
        if (targetCell) {
          targetCell.rowSpan = rowspan;
          targetCell.colSpan = colspan;
        }
      }
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '-1', j: 4 }, { i: '-1', j: 5 }, { i: '-1', j: 3 }, { i: '-1', j: 6 },  ], css_id: 'tinytable_css_pvqakw7gtdn62wneqnmq',}, 
          { positions: [ { i: '4', j: 1 }, { i: '4', j: 4 }, { i: '4', j: 2 }, { i: '4', j: 5 }, { i: '4', j: 3 }, { i: '4', j: 6 },  ], css_id: 'tinytable_css_705l54p8u2vmhlmot3g5',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '2', j: 1 }, { i: '1', j: 2 }, { i: '1', j: 5 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '3', j: 1 }, { i: '3', j: 4 }, { i: '1', j: 6 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 6 }, { i: '2', j: 5 }, { i: '3', j: 5 }, { i: '2', j: 6 },  ], css_id: 'tinytable_css_zg4s8u5uy8yhgcsfweql',}, 
          { positions: [ { i: '-1', j: 1 }, { i: '-1', j: 2 },  ], css_id: 'tinytable_css_jgakvi0xbd2jp33p0ogk',}, 
          { positions: [ { i: '0', j: 1 }, { i: '0', j: 4 }, { i: '0', j: 2 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 3 },  ], css_id: 'tinytable_css_dqasik54nf8d4t33vrk5',}, 
          { positions: [ { i: '4', j: 0 },  ], css_id: 'tinytable_css_6gsxgadwx9xcbywa7g3b',}, 
          { positions: [ { i: '1', j: 0 }, { i: '2', j: 0 }, { i: '3', j: 0 },  ], css_id: 'tinytable_css_m9ifvi3yxsczj2ok44it',}, 
          { positions: [ { i: '-1', j: 0 },  ], css_id: 'tinytable_css_p0pkkytbwcwn8uv1uqyw',}, 
          { positions: [ { i: '0', j: 0 },  ], css_id: 'tinytable_css_aw8mg97hno6bf2uykxrz',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  styleCell_s34u8ireasgobi6ae8ni(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <style>
      /* tinytable css entries after */
      .table td.tinytable_css_pvqakw7gtdn62wneqnmq, .table th.tinytable_css_pvqakw7gtdn62wneqnmq { text-align: right; text-align: center; border-top: solid #d3d8dc 0.1em; text-align: center; }
      .table td.tinytable_css_705l54p8u2vmhlmot3g5, .table th.tinytable_css_705l54p8u2vmhlmot3g5 { text-align: right; border-bottom: solid #d3d8dc 0.1em; }
      .table td.tinytable_css_zg4s8u5uy8yhgcsfweql, .table th.tinytable_css_zg4s8u5uy8yhgcsfweql { text-align: right; }
      .table td.tinytable_css_jgakvi0xbd2jp33p0ogk, .table th.tinytable_css_jgakvi0xbd2jp33p0ogk { text-align: right; text-align: center; border-top: solid #d3d8dc 0.1em; text-align: center; border-bottom: solid #d3d8dc 0.05em; }
      .table td.tinytable_css_dqasik54nf8d4t33vrk5, .table th.tinytable_css_dqasik54nf8d4t33vrk5 { text-align: right; border-bottom: solid #d3d8dc 0.05em; }
      .table td.tinytable_css_6gsxgadwx9xcbywa7g3b, .table th.tinytable_css_6gsxgadwx9xcbywa7g3b { text-align: left; border-bottom: solid #d3d8dc 0.1em; }
      .table td.tinytable_css_m9ifvi3yxsczj2ok44it, .table th.tinytable_css_m9ifvi3yxsczj2ok44it { text-align: left; }
      .table td.tinytable_css_p0pkkytbwcwn8uv1uqyw, .table th.tinytable_css_p0pkkytbwcwn8uv1uqyw { text-align: left; text-align: center; border-top: solid #d3d8dc 0.1em; text-align: center; }
      .table td.tinytable_css_aw8mg97hno6bf2uykxrz, .table th.tinytable_css_aw8mg97hno6bf2uykxrz { text-align: left; border-bottom: solid #d3d8dc 0.05em; }
    </style>
    <div class="container">
      <table class="table table-borderless" id="tinytable_s34u8ireasgobi6ae8ni" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <thead>
<tr>
<th scope="col" align="center" colspan="1" data-row="-1" data-col="0"> </th>
<th scope="col" align="center" colspan="2" data-row="-1" data-col="1">0</th>
<th scope="col" align="center" colspan="2" data-row="-1" data-col="2">1</th>
<th scope="col" align="center" colspan="1" data-row="-1" data-col="3"> </th>
<th scope="col" align="center" colspan="1" data-row="-1" data-col="4"> </th>
</tr>
        
              <tr>
                <th scope="col" data-row="0" data-col="0"> </th>
                <th scope="col" data-row="0" data-col="1">Mean</th>
                <th scope="col" data-row="0" data-col="2">Std. Dev.</th>
                <th scope="col" data-row="0" data-col="3">Mean</th>
                <th scope="col" data-row="0" data-col="4">Std. Dev.</th>
                <th scope="col" data-row="0" data-col="5">Diff. in Means</th>
                <th scope="col" data-row="0" data-col="6">Std. Error</th>
              </tr>
        </thead>
        
        <tbody>
                <tr>
                  <td data-row="1" data-col="0">age</td>
                  <td data-row="1" data-col="1">7.3</td>
                  <td data-row="1" data-col="2">4.2</td>
                  <td data-row="1" data-col="3">10.4</td>
                  <td data-row="1" data-col="4">3.4</td>
                  <td data-row="1" data-col="5">3.1***</td>
                  <td data-row="1" data-col="6">0.3</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="0">dewormed</td>
                  <td data-row="2" data-col="1">0.5</td>
                  <td data-row="2" data-col="2">0.5</td>
                  <td data-row="2" data-col="3">0.5</td>
                  <td data-row="2" data-col="4">0.5</td>
                  <td data-row="2" data-col="5">-0.0</td>
                  <td data-row="2" data-col="6">0.0</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="0">fur_length</td>
                  <td data-row="3" data-col="1">49.8</td>
                  <td data-row="3" data-col="2">10.2</td>
                  <td data-row="3" data-col="3">49.8</td>
                  <td data-row="3" data-col="4">10.1</td>
                  <td data-row="3" data-col="5">0.1</td>
                  <td data-row="3" data-col="6">0.7</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="0">weight</td>
                  <td data-row="4" data-col="1">21.4</td>
                  <td data-row="4" data-col="2">2.9</td>
                  <td data-row="4" data-col="3">22.3</td>
                  <td data-row="4" data-col="4">3.0</td>
                  <td data-row="4" data-col="5">0.9***</td>
                  <td data-row="4" data-col="6">0.2</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer</strong>: The balance sheet shows that there are confounding variables when estimating adoption speed by vaccination status. The difference in means for age(vaccinated dogs are on average 3.1 years older) and weight(vaccinated dogs are on average 0.9 kgs heavier) are signifigant which makes sense as the DGP explicitly states that age is linearly affects adoption speed.</p>
<p>Since age is a cofounder of adoption speed, vaccination status, and weight, it makes sense why weight is also giving some signifigant results. Vaccinated dogs are heavier since age affects weight and older dogs are heavier. However, since the DGP said the relationships listed are the only ones in affect, we know that weight doesn’t affect vaccination status.</p>
<p>Deworming status and fur length don’t have signifigant difference in means between vaccination statuses.</p>
<p>Thus, when running a regression to determine adoption speed from vaccination status, we should control for age.</p>
</div>
</div>
</div>
<p><strong>4.3 Causal Effect of Vaccination</strong></p>
<p>Based on your knowledge of the DGP, estimate a model that only includes the variables necessary to identify the effect of vaccination on adoption speed. Explain why you specified the model this way. Finally, calculate 95% confidence intervals for the effect of vaccination on adoption speed and interpret them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the library</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(estimatr)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="co"># create a model and control for age</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>robust_model <span class="ot">=</span> <span class="fu">lm_robust</span>(adoption_speed<span class="sc">~</span> vaccinated <span class="sc">+</span> age, <span class="at">data =</span> dog_data) </span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="co"># summarize the model and analyze confidence intervals</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(robust_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm_robust(formula = adoption_speed ~ vaccinated + age, data = dog_data)

Standard error type:  HC2 

Coefficients:
            Estimate Std. Error t value  Pr(&gt;|t|) CI Lower CI Upper  DF
(Intercept)  59.5981    0.56975 104.604 0.000e+00  58.4800   60.716 997
vaccinated    4.6110    0.58754   7.848 1.086e-14   3.4580    5.764 997
age          -0.8395    0.06395 -13.128 1.984e-36  -0.9649   -0.714 997

Multiple R-squared:  0.1666 ,   Adjusted R-squared:  0.1649 
F-statistic: 93.17 on 2 and 997 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(robust_model, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %     97.5 %
(Intercept) 58.4800313 60.7161236
vaccinated   3.4580165  5.7639268
age         -0.9649439 -0.7139766</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Answer">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Answer</strong>: I chose to create a robust linear regression to model the relationship between vaccination status an adoption speed because as seen in my DAG (information from the DGP), there is a backdoor path to adoption speed as age effects both vaccination status and adoption speed(it is a cofounder). By adding age into my model, I can control for this and get only the effect of vaccination of adoption speed.</p>
<p>The 95% confidence interval results suggest that if the dogs are not vaccinated (VS=0) and are 0 years old within this distribtuion, we are 95% sure their adoption speed is between 58.48 and 60.72. We are also 95% confident that the true coefficient for vaccination status on adoption speed is between 3.46 to 5.76 units (keeping age constant).</p>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>